### ISSUE TITLE
 json file as database for already downloaded torrents

### ISSUE THREAD

**Issue by rj-d2** [BreadedChickenator/Cross-Seed-AutoDL#3]
hi,

thanks for making this work on linux,
would it be possible to add a simple json file as database for already downloaded torrents?
so the files are not getting downloaded over and over again

thx

**Comment by BC44** [comment]
Sure. I'll add this soon

**Comment by BC44** [comment]
Today I was working on switching the script over to a commandline-based script. I've also added the option to work with a single downloaded item, so that you can simply run the script upon that newly downloaded file instead of parsing every single item in your download directory whenever you download something new, which is what I think you were doing.

I'll still add the json history file in any case.

**Comment by BC44** [comment]
Added history file in f232234cbde1be492de937537259c5e99eec961a
